/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'onome' at '10/22/17 2:35 PM' with Gradle 2.14.1
 *
 * @author onome, @date 10/22/17 2:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
